steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/multi-client', './client']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/multi-server', './server']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/multi-worker', './worker']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/multi-client']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/multi-server']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/multi-worker']
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'set', 'image', 'deployments/client-deployment', 'client=gcr.io/$PROJECT_ID/multi-client']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=multi-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'set', 'image', 'deployments/server-deployment', 'server=gcr.io/$PROJECT_ID/multi-server']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=multi-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'set', 'image', 'deployments/worker-deployment', 'worker=gcr.io/$PROJECT_ID/multi-worker']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=multi-cluster'
images:
- 'gcr.io/$PROJECT_ID/multi-client'
- 'gcr.io/$PROJECT_ID/multi-server'
- 'gcr.io/$PROJECT_ID/multi-worker'
